language: node_js
node_js:
  - "8.11.2"
cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $github_token
  local-dir: build
  on:
    branch: master
