version: '3'
services:
  frontend:
    image: aspgems/react-ordering
    command: npm start
    entrypoint: /teamleader/scripts/entrypoint.sh
    depends_on:
      - "backend"
    ports:
      - 3000:3000
    volumes:
      - .:/teamleader:delegated
  backend:
    build: .
    image: aspgems/react-ordering
    command: [json-server, --watch, /var/jsondb/db.json]
    ports:
      - 3001:3001
  storybook:
    image: aspgems/react-ordering
    command: npm run storybook
    depends_on:
      - "backend"
    ports:
      - 9001:9001
