version: '3'
services:
  frontend:
    build: .
    command: npm start
    entrypoint: /teamleader/scripts/entrypoint.sh
    depends_on:
      - "backend"
    ports:
      - 3000:3000
    volumes:
      - .:/teamleader:delegated
  backend:
    build: .
    command: npm run start-server
    ports:
      - 3001:3001
  storybook:
    build: .
    command: npm run storybook
    depends_on:
      - "backend"
    ports:
      - 9001:9001
